apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: api-srv
profiles:
  - name: api-srv
    build:
      artifacts:
        - image: api-srv
          docker:
            dockerfile: Dockerfile
      local:
        useDockerCLI: true
        useBuildkit: true
      tagPolicy:
        customTemplate:
          template: "{{.DATE}}"
          components:
            - name: DATE
              dateTime:
                format: "2006-01-02"
                timezone: "Asia/Taipei"
    manifests:
      rawYaml:
        - deploy/k8s/*.yaml
