apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: api-srv
profiles:
  - name: api-srv
    build:
      artifacts:
        - image: <account-ID>.dkr.ecr.ap-northeast-1.amazonaws.com/api-srv
          docker:
            dockerfile: Dockerfile
      local:
        useDockerCLI: true
        useBuildkit: true
      tagPolicy:
        sha256: {}
    manifests:
      rawYaml:
        - deploy/k8s/*.yaml
