apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-srv
  labels:
    app: api-srv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-srv
  template:
    metadata:
      labels:
        app: api-srv
    spec:
      containers:
        - name: api-srv
          image: <account-ID>.dkr.ecr.ap-northeast-1.amazonaws.com/api-srv
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - name: rest
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
